name: Build and deploy Python app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws configure set aws_access_key_id ${{ secrets.AKIATKTSM3F6AWWX7AKG }}
          aws configure set aws_secret_access_key ${{ secrets.XvA7YYMp6AinU+H0kTKs/zZkqVJCQN8CNMj4rgYw }}
          aws elasticbeanstalk create-application-version --application-name YourApplicationName --version-label $GITHUB_SHA --source-bundle S3Bucket=elasticbeanstalk-source-bucket,S3Key=$GITHUB_SHA
          aws elasticbeanstalk update-environment --environment-name YourEnvironmentName --version-label $GITHUB_SHA
